### PR TITLE
use the chain name as a blockchain alias

### PR DESCRIPTION
**Pull request by boulix3**
Related to the issue #476 
I chose to use the subnet name as the blockchain alias. I figured it was not useful to ask for another parameter since there can only have one chain per subnet with avalanche-cli.

### CODE REVIEW

**Comment by boulix3** [comment]
Here is an example with a subnet-evm.
You can make the same query with the alias or the blockchainId in the rpc url.

```shell
$ curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"eth_baseFee",
    "params" :[]
}' -H 'content-type:application/json;' http://127.0.0.1:9650/ext/bc/mysubnet/rpc
{"jsonrpc":"2.0","id":1,"result":"0x5d21dba00"}
$ curl -X POST --data '{
    "jsonrpc":"2.0",
    "id"     :1,
    "method" :"eth_baseFee",
    "params" :[]
}' -H 'content-type:application/json;' http://127.0.0.1:9650/ext/bc/2VqqvGNY71aVWm1V29HvNiv6TrdHvpg3kvceKVYP2PVrcVUe6A/rpc
{"jsonrpc":"2.0","id":1,"result":"0x5d21dba00"}
```

**Comment by boulix3** [comment]
Here is a screenshot of the subnet creation wizard output where we can see the ALIASURL column.
subnet-alias

**Comment by boulix3** [comment]
@dasconnor can you please check this out?

**Review by dasconnor — COMMENTED** [review]
If you fix the failing tests, we can merge this

**Comment by boulix3** [comment]
> If you fix the failing tests, we can merge this

It's fixed.

**Comment by dasconnor** [comment]
Sorry, one last ask, can you sign your commit? https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by dasconnor** [comment]
All merged! It'll go out in the next release, probably later this week.

**Pull request merged**
