### PR TITLE
fixes #667 related to Banff.10, changing config-keys from "whitelisted-subnets" to "track-subnets"

### LINKED ISSUE #667: Config-Setting "whitelisted-subnets" has been renamed to "track-subnets"
According to [Banff.10 release page](https://github.com/ava-labs/avalanchego/releases),  the setting has been removed in favor of the new option "track-subnets". However, the CLI-tool still produces config-files with the old setting.

Old: "whitelisted-subnets"
```
{
  "whitelisted-subnets": "xxxxx"
}
```

New:

```
{
  "track-subnets": "yyyy"
}
```

### PR DESCRIPTION
**Pull request by itinance**
The setting `whitelisted-subnets` has been removed and renamed to  `track-subnets`.

This PR writes back all settings to the new key, while backward compatibility is given that the old key will still be read if the new key is not present. Also, the old-key will be removed in favor of the new setting.

I also provided unit-tests for "avagoConfig.go" to ensure that everything works as expected.

### CODE REVIEW

**Comment by dasconnor** [comment]
If you can fix the lint, we will merge this

**Comment by dasconnor** [comment]
The lint and the e2e tests

**Comment by dasconnor** [comment]
Going to merge this into a separate branch so I can fix the PR issues

**Comment by itinance** [comment]
Hey, many thanks. The Avalanche Summit took too much attention here on my end for planning and getting some stuff ready. My plan to catch up here was tomorrow (my travel day to the summit). Pls tell me if I can assist further here in this PR 👍

**Pull request merged**
