### PR TITLE
Shebang that works in more systems. Advances #1498

### PR DESCRIPTION
**Pull request by vtamara**
Advances #1498

### CODE REVIEW

**Review by arturrez — APPROVED** [review]
thank you. these are nice nits

**Comment by arturrez** [comment]
@vtamara can you please sign your commit

**Comment by vtamara** [comment]
> @vtamara can you please sign your commit

Signed. Thank you.

**Comment by vtamara** [comment]
Blessings @arturrez and community, since the effort of porting to OpenBSD has brought improvements in security I wanted you to notice that I applied for funding in the "Avalanche Community Grants Quadratic Funding Round One" to do a deeper audit of the sources of the fundamental tools of Avalanche, complete the porting and test more fully.   Could you please vote for the project at: https://explorer.gitcoin.co/#/round/43114/4/28 ?

**Pull request merged**
